
server:
  port: 9009

mybatis-plus:
  mapper-locations: classpath:com/ken/role/mapper/xml/*.xml
  configuration:
    default-statement-timeout: 3

spring:
  application:
    name: mybatis_plus
  datasource:
    dynamic:
      primary: master  #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:      #默认数据源
          url: jdbc:mysql://localhost:3306/vhr?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
          username: root
          password: root
          driver-calss-name: com.mysql.cj.jdbc.Driver

        db02:
          url: jdbc:mysql://localhost:3306/demo2?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
          username: root
          password: root
          driver-calss-name: com.mysql.cj.jdbc.Driver

        db03:
          url: jdbc:mysql://localhost:3306/demo?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
          username: root
          password: root
          driver-calss-name: com.mysql.cj.jdbc.Driver
